#!/usr/bin/sh
# river/init
# @author nate zhou
# @since 2025,2026

# https://codeberg.org/unixchad/kwm
# https://github.com/gnuunixchad/kwm
${HOME}/.local/bin/prepare-damblocks-fifo
/usr/local/bin/kwm &
